version: '2'

services:
  postgres:
    image: mdillon/postgis:9.6

  location_app:
    container_name: location-app
    build:
      context: ./location_app
      dockerfile: Dockerfile
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py makemigrations &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
