# Generated by Django 2.2.13 on 2020-07-20 17:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1000)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True)),
                ('elevation', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
